### ISSUE TITLE
parquet does not compile with `features=["zstd"]`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#1630]
reported by @zeroflaw

A project with 

`parquet = { version = "12.0.0", default-features = false, features = ["zstd"] }`

Fails to compile with

`format!("{}", dt.format("%Y-%m-%d %H:%M:%S %:z"))
    |                      ^^^^^^ method not found in DateTime<Utc>`

https://github.com/apache/arrow-rs/blob/7da41c7328820241a1e9a06eb83cade2e1f08da4/parquet/Cargo.toml#L41

This should not have default-features = false

_Originally posted by @zeroflaw in https://github.com/apache/arrow-rs/issues/1623#issuecomment-1113196552_

**Comment by alamb** [comment]
One way to work around this is to manually add a dependency on `chrono` with the correct features, such as

```toml
chrono = { version = "0.4" }
parquet = { version = "12.0.0", default-features = false, features = ["zstd"] }
```
