### ISSUE TITLE
Optimize Writing of Bloom Filters

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-rs#3320]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-rs/issues/3318 highlighted that the current performance of writing bloom filters leaves a lot to be desired. This is a placeholder ticket for tracking improving this situation

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by viirya** [comment]
Currently we achieve the following:

```
write_batch primitive/4096 values primitive with bloom filter                                                                                                                                                                          
                        time:   [3.9911 ms 4.0027 ms 4.0151 ms]                                                                                                                                                                        
                        thrpt:  [43.965 MiB/s 44.100 MiB/s 44.229 MiB/s]                                                                                                                                                               
                 change:                                                                                                                                                                                                               
                        time:   [-18.041% -17.601% -17.194%] (p = 0.00 < 0.05)                                                                                                                                                         
                        thrpt:  [+20.764% +21.360% +22.012%]                                                                                                                                                                           
                        Performance has improved.                                                                                                                                                                                      
write_batch primitive/4096 values primitive non-null with bloom filter                                                                                                                                                                 
                        time:   [3.9366 ms 3.9445 ms 3.9530 ms]                                                                                                                                                                        
                        thrpt:  [43.791 MiB/s 43.885 MiB/s 43.972 MiB/s]                                                                                                                                                               
                 change:                                                                                                                                                                                                               
                        time:   [-16.064% -15.526% -15.016%] (p = 0.00 < 0.05)                                                                                                                                                         
                        thrpt:  [+17.669% +18.379% +19.139%]                                                                                                                                                                           
                        Performance has improved.                                                                                                                                                                                      
write_batch primitive/4096 values string with bloom filter
                        time:   [778.11 µs 778.54 µs 779.02 µs]
                        thrpt:  [102.23 MiB/s 102.29 MiB/s 102.34 MiB/s]
                 change:
                        time:   [-41.408% -40.747% -40.069%] (p = 0.00 < 0.05)
                        thrpt:  [+66.857% +68.769% +70.670%]
                        Performance has improved.
write_batch primitive/4096 values string dictionary with bloom filter
                        time:   [392.89 µs 397.73 µs 403.93 µs]
                        thrpt:  [119.18 MiB/s 121.04 MiB/s 122.53 MiB/s]
                 change:
                        time:   [-35.315% -33.950% -32.450%] (p = 0.00 < 0.05)
                        thrpt:  [+48.040% +51.400% +54.596%]
                        Performance has improved.
write_batch primitive/4096 values string non-null with bloom filter
                        time:   [844.48 µs 846.53 µs 850.05 µs]
                        thrpt:  [92.534 MiB/s 92.919 MiB/s 93.145 MiB/s]
                 change:
                        time:   [-42.406% -41.573% -40.784%] (p = 0.00 < 0.05)
                        thrpt:  [+68.873% +71.153% +73.630%]
                        Performance has improved.
```

Maybe we can close this.
