### ISSUE TITLE
Pull Request Labeler is not working

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#462]
**Describe the bug**
The automatic labeler job  (in Dev PR / "Process")  https://github.com/apache/arrow-rs/blob/master/.github/workflows/dev_pr.yml#L23-L39 is supposed to label Pull Requests based on what files they change, but it does not appear to be working

**To Reproduce**
Make a PR

**Expected behavior**
PRs should automatically be labeled with `arrow`, `parquet`, etc labels depending on what files are changed;

**Additional context**
The labeler came from the original in arrow: https://github.com/apache/arrow/blob/master/.github/workflows/dev_pr.yml#L65-L74

Which seems to be working

**Comment by Dandandan** [comment]
Checking the difference yields:

```
on:
  # TODO: Enable this when eps1lon/actions-label-merge-conflict is available.
  # push:
  #   branches:
  #     - master
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
```

This version:

```
on:
  pull_request:
```
