### ISSUE TITLE
object-store: http-store fails when url doesn't have last-modified header on 0.7.0

### ISSUE THREAD

**Issue by universalmind303** [apache/arrow-rs#4831]
**Describe the bug**
prior to `0.7.0` of object_store, you could fetch from urls that didn't have `last-modified` header, after 0.7.0 i get the error
```
 Unable to extract metadata from headers: Last-Modified Header missing from response
 ```

**To Reproduce**
cargo.toml
```toml
[package]
name = "object-store-mre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object_store = { version = "0.7.0", features = ["http", "aws", "azure", "gcp"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
```
main.rs
```rust
use object_store::http::HttpBuilder;
use object_store::path::Path;
use object_store::ObjectStore;

#[tokio::main]
async fn main() {
    let http = HttpBuilder::new().with_url("https://raw.githubusercontent.com/GlareDB/glaredb/main/testdata/sqllogictests_datasources_common/data/bikeshare_stations.ndjson");
    let store = http.build().unwrap();
    let path = Path::default();

    let res = store.get(&path).await.unwrap();
    println!("{:?}", res);
}
```

**Expected behavior**
works like it did in previous versions

**Additional context**
