### ISSUE TITLE
object_store: Support for Azure Microsoft Entra for authentication from AKS

### ISSUE THREAD

**Issue by gianarb** [apache/arrow-rs#5115]
**Which part is this question about**

object_store/azure

**Describe your question**

I use the method described here to authenticate containers running in Azure AKS:

https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet

In practice I have a service account that looks like this:

```
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: afgd
    azure.workload.identity/tenant-id: 44hb
  creationTimestamp: "2023-11-22T11:47:33Z"
  labels:
    environment: test
  name: blob-access
  namespace: default
```

And I annotation the pod I want to authenticate as described in the documentation.

It worked out of the box for the containers written in other language (Go) but not for the one I have in Rust that uses datafusion.

This is the way I build the azure client:

```rust
MicrosoftAzureBuilder::from_env()
  .with_url(c.account)
  .with_container_name(c.container_name)
  .build()
  .unwrap()
```

I can't figure out the right way to make this authentication method to work
**Additional context**

The error I get looks like this one https://github.com/apache/arrow-rs/issues/4096
